"""Products

Revision ID: 635f35b73426
Revises: c7da0893813f
Create Date: 2022-08-10 20:49:25.838539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '635f35b73426'
down_revision = 'c7da0893813f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('product_id', sa.String(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('product_id')
    )
    op.create_index(op.f('ix_products_external_id'), 'products', ['external_id'], unique=False)
    op.create_index(op.f('ix_products_product_id'), 'products', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_product_id'), table_name='products')
    op.drop_index(op.f('ix_products_external_id'), table_name='products')
    op.drop_table('products')
    # ### end Alembic commands ###
